version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity (not recommended for production)
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polyglot-docs-app
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=127.0.0.1
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INDEX=polyglot-documents
    ports:
      - "8080:8080"
    networks:
      - esnet
    volumes:
      - ./logs:/app/logs

networks:
  esnet:
    driver: bridge

volumes:
  esdata:
    driver: local
